
import Navbar from "./components/NavigationBar/Navbar";
import "./globals.css";


export const metadata = {
  title: "Manimalist Anime",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-outfit bg-[#F6F8FF]`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
