
import Navbar from "@/components/navigationbar/Navbar";
import "./globals.css";
import TanstackProvider from "@/providers/TanstackProvider";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "Manimalist Anime",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased font-neu bg-bg`}>
        <TanstackProvider>
          <div className="flex flex-col min-h-screen">
            <Navbar className="flex-none" />
            <main className="flex-grow flex items-center justify-center">
              {children}
            </main>
            <Footer className="flex-none" />
          </div>
        </TanstackProvider>
      </body>
    </html>
  );
}
