
import Navbar from "@/components/navigationbar/Navbar";
import "./globals.css";
import TanstackProvider from "@/providers/TanstackProvider";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "Manimalist Anime",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased font-outfit dark:bg-color-dark bg-color-day`}>
        <TanstackProvider>
          <Navbar />
          {children}
          <Footer />
        </TanstackProvider>
      </body>
    </html>
  );
}
